version: 0.2
phases:
  pre_build:
    commands:
      - sudo apk add dotnet6-sdk -y
      - sudo apk add aspnetcore6-runtime -y
      - sudo apk add dotnet6-runtime -y
      - echo Restore started on `date`
      - dotnet restore MVC_Core_WebApp/MVC_Core_WebApp.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output MVC_Core_WebApp/MVC_Core_WebApp.csproj
artifacts:
  files:
    - ./**/*
  base-directory: './build_output'