version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      #- dotnet restore MVC_Core_Publish/MVC_Core_WebApp.deps.json
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output  MVC_Core_Publish/MVC_Core_WebApp.deps.json
artifacts:
  files:
    - ./**/*
  base-directory: './build_output'